window.PUBLICATIONS = [
  {
    "No": "",
    "Year": "2026",
    "Category": "AI & Computational Design",
    "Keywords": "AI, Neural Operator, Physics-guided Simulation, Electromagnetic Field Prediction, Nanophotonics",
    "Title": "Broadband Electromagnetic Field Prediction at Unseen Wavelengths via Physics-Guided Neural Operators",
    "Authors": "J. Seo†, [[b]]C. Kang†[[/b]], D. Seo, [[b]]H. Chung*[[/b]]",
    "Journal": "Nanophotonics (Under review)",
    "Link": "https://arxiv.org/abs/2408.02971",
    "Image": "https://drive.google.com/thumbnail?id=1l5n8G9cc9Zths0I72hzBv1u8OdHRJMkg&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Neural Operator",
    "Note": "",
    "MemberKeys": "chanik-kang; haejun-chung"
  },
  {
    "No": "",
    "Year": "2026",
    "Category": "Imaging & Display",
    "Keywords": "Color Router, Inverse Design, Angle Robustness, Image Sensor, Structural Similarity",
    "Title": "Inverse Design of Angle-Robust Color Routers by Optical Structural Similarity",
    "Authors": "[[b]]Donghyun Kim[[/b]], [[b]]J. Han[[/b]], [[b]]S. Lee[[/b]], M. Jang, [[b]]H. Chung*[[/b]]",
    "Journal": "ACS Photonics (Under review)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1MLTUfcFiExZlRvH4TnVizR-BvzyeBW3G&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Color Router / Inverse Design",
    "Note": "",
    "MemberKeys": "donghyun-kim; junseo-han; seunghyeon-lee; haejun-chung"
  },
  {
    "No": "",
    "Year": "2026",
    "Category": "Nanophotonics & Inverse Design",
    "Keywords": "Metasurface, Optical Skyrmion, Topological Photonics, Inverse Design",
    "Title": "Inverse-Designed Metasurfaces for Compact Optical Skyrmion Generation with High Topological Fidelity",
    "Authors": "[[b]]D. Park[[/b]], A. Song, [[b]]H. Chung*[[/b]], S. Kim*",
    "Journal": "Advanced Optical Materials (Under review)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Metasurface / Optical Skyrmion",
    "Note": "",
    "MemberKeys": "donghyun-park; haejun-chung"
  },
  {
    "No": "[52]",
    "Year": "2026",
    "Category": "Integrated Photonics & Quantum",
    "Keywords": "Thin-Film Lithium Niobate, Two-Photon Interference, On-Chip Photonics, Quantum Photonics",
    "Title": "Versatile On-Chip Reconfigurable Two-Photon Interference Platforms Using Thin-Film Lithium Niobate",
    "Authors": "[[b]]Minho Choi‡[[/b]], Changhyun Kim‡, Sunghyun Moon, Hyeon Hwang, Min-Kyo Seo, Hyang-Tag Lim, [[b]]Haejun Chung[[/b]], Hojoong Jung*, and [[b]]Hyounghan Kwon*[[/b]]",
    "Journal": "APL Photonics (2026) (IF:5.3, JCR~20%)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Integrated Photonics",
    "Note": "Front Cover selected",
    "MemberKeys": "minho-choi; haejun-chung; hyounghan-kwon"
  },
  {
    "No": "[51]",
    "Year": "2026",
    "Category": "AI & Computational Design",
    "Keywords": "AI, Ordinal Classification, Calibration, Dynamic Regularization, Unimodality",
    "Title": "MORCU: Margin-Based Ordinal Classification with Dynamic Regularization for Calibration and Unimodality",
    "Authors": "[[b]]Daehwan Kim[[/b]], [[b]]H. Chung*[[/b]], [[b]]I. Jang*[[/b]]",
    "Journal": "Pattern Recognition (2026) (IF:7.6, JCR~9%)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=18CqxGaHeYXT8XvwVVHZT__NfDBRxXbWW&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Ordinal Classification",
    "Note": "Editor's pick",
    "MemberKeys": "daehwan-kim; haejun-chung; ikbeom-jang"
  },
  {
    "No": "[50]",
    "Year": "2026",
    "Category": "Biomedical AI",
    "Keywords": "AI, Medical Imaging, MRI, PET, Cross-modal Synthesis, Perceptual Loss",
    "Title": "Cyclic 2.5D Perceptual Loss for Cross-Modal 3D Image Synthesis: T1 MRI to Tau-PET",
    "Authors": "[[b]]J. Moon[[/b]], S. Kim, [[b]]H. Chung*[[/b]], [[b]]I. Jang*[[/b]]",
    "Journal": "Human Brain Mapping (2026) (IF:3.5, JCR~17%)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=15A6ZB8umxQafZntlr2AnR7ZGRAeZtrUj&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Medical Imaging",
    "Note": "",
    "MemberKeys": "junho-moon; haejun-chung; ikbeom-jang"
  },
  {
    "No": "[49]",
    "Year": "2026",
    "Category": "AI & Computational Design",
    "Keywords": "AI, Multi-View Fusion, Mutual Distillation, View Combination",
    "Title": "Hierarchical Mutual Distillation for Multi-View Fusion: Learning from All Possible View Combinations",
    "Authors": "[[b]]J. Yang[[/b]], [[b]]H. Chung*[[/b]], [[b]]I. Jang*[[/b]]",
    "Journal": "Pattern Recognition (2026) (IF:7.6, JCR~9%)",
    "Link": "https://arxiv.org/abs/2411.10077",
    "Image": "https://drive.google.com/thumbnail?id=1g-eK6hJ-jj2r72pjjHQWbxFzXiHeUTva&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Multi-View Fusion",
    "Note": "",
    "MemberKeys": "jiwoong-yang; haejun-chung; ikbeom-jang"
  },
  {
    "No": "[48]",
    "Year": "2026",
    "Category": "Nanophotonics & Inverse Design",
    "Keywords": "Topology Optimization, Adjoint Method, Time-domain Simulation, Band-selective Design",
    "Title": "Multi-objective time-domain adjoint via temporal convolution for band-selective electromagnetic topology optimization",
    "Authors": "[[b]]M. Park[[/b]], S. Boriskina, [[b]]H. Chung*[[/b]]",
    "Journal": "Result in Physics (2026) (IF:4.8, JCR~20%)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=151E7xjWXHlytXB4I87EacEuIMtyYGAgn&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Topology Optimization",
    "Note": "",
    "MemberKeys": "mingyu-park; haejun-chung"
  },
  {
    "No": "[47]",
    "Year": "2026",
    "Category": "AI & Computational Design",
    "Keywords": "AI, Ranking, Human-in-the-loop, VLM, Pairwise Comparison",
    "Title": "Dodgersort: Uncertainty-Aware VLM-Guided Human-in-the-Loop Pairwise Ranking",
    "Authors": "[[b]]Y. Park[[/b]], [[b]]H. Chung*[[/b]], [[b]]I. Jang*[[/b]]",
    "Journal": "PAKDD (2026) (BK21 Conference, Oral Presentation)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=140jx8L40isqDLXK1toX4AR-fT63fFK8Y&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Human-in-the-loop Ranking",
    "Note": "",
    "MemberKeys": "yujin-park; haejun-chung; ikbeom-jang"
  },
  {
    "No": "[46]",
    "Year": "2026",
    "Category": "Nanophotonics & Inverse Design",
    "Keywords": "AI, Diffusion Model, Inverse Design, Fabrication-aware Design, Photonic Devices",
    "Title": "Physics-guided and fabrication-aware inverse design of photonic devices using diffusion models",
    "Authors": "Dongjin Seo†, Soobin Um†, Sangbin Lee, Jong Chul Ye* and [[b]]Haejun Chung*[[/b]]",
    "Journal": "ACS Photonics (2026) (IF:6.7, JCR 14%)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1DlfNuZXZgDGYt9I9PVD2CMqj5vrif1l1&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Inverse Design / Diffusion Model",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[45]",
    "Year": "2026",
    "Category": "Imaging & Display",
    "Keywords": "AI, Metalens Imaging, Image Translation, Image Synthesis",
    "Title": "Metalens-Style Image Synthesis for Metalens Imaging via Image-to-Image Translation",
    "Authors": "[[b]]Chanik Kang†[[/b]], [[b]]Hyewon Suk†[[/b]], Joonhyuk Seo, [[b]]Ikbeom Jang*[[/b]] and [[b]]Haejun Chung*[[/b]]",
    "Journal": "Scientific Report (2026) (IF:3.9, JCR~25%)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1BNodV-BaSe8wwxBmsj9tTNWa-LySZn7j&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Metalens Imaging",
    "Note": "",
    "MemberKeys": "chanik-kang; hyewon-suk; ikbeom-jang; haejun-chung"
  },
  {
    "No": "[44]",
    "Year": "2026",
    "Category": "Imaging & Display",
    "Keywords": "Thermal Imaging, Metalens, Inverse Design, Microbolometer, Wide FOV",
    "Title": "Inverse Design of Thermal Imaging Metalens Achieving 100 degrees Field-of-View on a 4 × 4 Microbolometer Array",
    "Authors": "[[b]]Munseong Bae†[[/b]], [[b]]Eunbi Jang†[[/b]], [[b]]Chanik Kang†[[/b]], [[b]]Haejun Chung*[[/b]]",
    "Journal": "Micromachines (2026) (IF:3.0)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=13QhVD8k9NZry6iZmAKCF4lZmZYO1ALf_&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Thermal Metalens",
    "Note": "",
    "MemberKeys": "munseong-bae; eunbi-jang; chanik-kang; haejun-chung"
  },
  {
    "No": "[43]",
    "Year": "2026",
    "Category": "Imaging & Display",
    "Keywords": "Color Router, Nanophotonics, Inverse Design, Oblique Incidence, Image Sensor",
    "Title": "Inverse Design of Nanophotonic Color Router Robust to Oblique Incidence",
    "Authors": "Jaehyun Jeon, Chanhyung Park, Doyoung Heo, [[b]]Haejun Chung[[/b]], Min Seok Jang*",
    "Journal": "Advanced Optical Materials (2026) (IF:7.2)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1Hg0hu5iR46ou5JkTEFsN8uLkcV7cI81Y&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Color Router / Nanophotonics",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "",
    "Year": "2026",
    "Category": "Biomedical AI",
    "Keywords": "AI, fMRI, Brain Network, Resting-State fMRI, Task fMRI",
    "Title": "BOLDSimNet: Examining Brain Network Similarity between Task and Resting-State fMRI",
    "Authors": "[[b]]B. Kim[[/b]], DD. Chakladar, [[b]]H. Chung*[[/b]], [[b]]I. Jang*[[/b]]",
    "Journal": "Under review",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1dZlSZclYn0od0DtsvMOGwFYTnwyJ6cp6&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / fMRI",
    "Note": "",
    "MemberKeys": "boseong-kim; haejun-chung; ikbeom-jang"
  },
  {
    "No": "",
    "Year": "2026",
    "Category": "AI & Computational Design",
    "Keywords": "AI, Ordinal Regression, Calibration, Neural Network",
    "Title": "Calibration of ordinal regression networks",
    "Authors": "[[b]]D. Kim[[/b]], [[b]]H. Chung*[[/b]], [[b]]I. Jang*[[/b]]",
    "Journal": "Under review",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1KZ4H1GW0b8eW5KeCDqvNjD9GOM2XWQkf&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Ordinal Regression",
    "Note": "",
    "MemberKeys": "daehwan-kim; haejun-chung; ikbeom-jang"
  },
  {
    "No": "",
    "Year": "2026",
    "Category": "AI & Computational Design",
    "Keywords": "AI, Ranking, Human-in-the-loop, Metalens Image Quality",
    "Title": "MetaRanker: Human-in-the-loop Active Ranking for Metalens Image Quality",
    "Authors": "[[b]]Y. Park[[/b]], [[b]]H. Chung*[[/b]], [[b]]I. Jang*[[/b]]",
    "Journal": "Under review",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1GFha3ddmm1lgtUb--pYdYlPWS1xswmMz&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Ranking",
    "Note": "",
    "MemberKeys": "yujin-park; haejun-chung; ikbeom-jang"
  },
  {
    "No": "",
    "Year": "2026",
    "Category": "AI & Computational Design",
    "Keywords": "Neural Operator, Fourier Neural Operator, Adjoint Method, Meta-optics, Inverse Design",
    "Title": "Neural Adjoint Method for Meta-optics: Accelerating Volumetric Inverse Design via Fourier Neural Operators",
    "Authors": "[[b]]C. Kang[[/b]], [[b]]H. Suk[[/b]], [[b]]H. Chung*[[/b]]",
    "Journal": "Under review",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1vXqSty2QbHfJyZXec9RzjdS0KKssHQY7&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Neural Operator / Meta-optics",
    "Note": "",
    "MemberKeys": "chanik-kang; hyewon-suk; haejun-chung"
  },
  {
    "No": "",
    "Year": "2026",
    "Category": "Materials & Light-Matter Interaction",
    "Keywords": "2D Materials, WS2, Plasmonics, Nanocubes, Valley-polarized Emission",
    "Title": "Enhanced valley-polarized emission in n-doped WS2 via plasmonic nanocubes",
    "Authors": "Ha Young Lee, [[b]]Munseong Bae[[/b]], Alexander Corletto, Feier Fang, James Bullock, [[b]]Haejun Chung[[/b]], and Sejeong Kim*",
    "Journal": "Under review",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "2D Materials / Plasmonics",
    "Note": "",
    "MemberKeys": "munseong-bae; haejun-chung"
  },
  {
    "No": "",
    "Year": "2026",
    "Category": "Materials & Light-Matter Interaction",
    "Keywords": "2D Materials, Optical Vortex, van der Waals Materials, High Efficiency",
    "Title": "Near-unity efficiency optical vortex generation in van der Waals materials",
    "Authors": "Sujeong Byun, [[b]]Munseong Bae[[/b]], Hangsung Cho, [[b]]Haejun Chung[[/b]], Kostya Novoselov, James Bullock and Sejeong Kim*",
    "Journal": "Under review",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "2D Materials / Optical Vortex",
    "Note": "",
    "MemberKeys": "munseong-bae; haejun-chung"
  },
  {
    "No": "[42]",
    "Year": "2025",
    "Category": "Imaging & Display",
    "Keywords": "AR, Waveguide Coupler, Inverse Design, Optical See-through Display",
    "Title": "Optical see-through augmented reality via inverse-designed waveguide couplers",
    "Authors": "[[b]]Seunghyun Lee[[/b]], Byounghyo Lee and [[b]]Haejun Chung*[[/b]]",
    "Journal": "Nanophotonics (2025) (IF:7.5)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1PUFTgaGgj7vx7j-uFOGRZe4S-FrpupAh&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AR / Waveguide Coupler",
    "Note": "",
    "MemberKeys": "seunghyeon-lee; haejun-chung"
  },
  {
    "No": "[41]",
    "Year": "2025",
    "Category": "Materials & Light-Matter Interaction",
    "Keywords": "Chiral Nanophotonics, Chiroptical Response, Inverse Design",
    "Title": "Inverse design for enhanced chiroptical response with chiral nanophotonic structures",
    "Authors": "[[b]]Munseong Bae†[[/b]], Chia-Chun Pan†, [[b]]Chanik Kang†[[/b]], [[b]]Jinseong Bae[[/b]], [[b]]Donghyun Park[[/b]], Seokho Lee, Cherry Park, Haoran Ren, Junsuk Rho, [[b]]Haejun Chung*[[/b]], and Sejeong Kim*",
    "Journal": "APL Photonics (2025) (IF:5.3, JCR 18%)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1Kv3alx2rJ9x8r3aXYSlJ-pY1l9KuNt_6&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Chiral Nanophotonics",
    "Note": "",
    "MemberKeys": "munseong-bae; chanik-kang; jinseong-bae; donghyun-park; haejun-chung"
  },
  {
    "No": "[40]",
    "Year": "2025",
    "Category": "AI & Computational Design",
    "Keywords": "AI, Sorting, Human-in-the-loop, CLIP, Pairwise Comparison",
    "Title": "EZ-Sort: Efficient Pairwise Comparison via Zero-Shot CLIP-Based Pre-Ordering and Human-in-the-Loop Sorting",
    "Authors": "[[b]]Y. Park[[/b]], [[b]]H. Chung*[[/b]], [[b]]I. Jang*[[/b]]",
    "Journal": "CIKM (2025) (BK21 Conference)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=15O2l-ei6mjvHZXWp4Lk9fS9z5k5Bioe-&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Sorting",
    "Note": "",
    "MemberKeys": "yujin-park; haejun-chung; ikbeom-jang"
  },
  {
    "No": "[39]",
    "Year": "2025",
    "Category": "Materials & Light-Matter Interaction",
    "Keywords": "2D Materials, Optical Vortex, Spin-Orbit Coupling, van der Waals Materials",
    "Title": "Spin-Orbit Coupling for Optical Vortex Generation in van der Waals Materials",
    "Authors": "J. Jo†, S. Byun†, [[b]]M. Bae[[/b]], J. Wang, [[b]]H. Chung*[[/b]], S. Kim*",
    "Journal": "Light: Science & Applications (2025) (IF:23.4, JCR~2.9%)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1lk0YuAuu2fVAF4oKVEjg_FzhPTpqRmC0&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "2D Materials / Optical Vortex",
    "Note": "",
    "MemberKeys": "munseong-bae; haejun-chung"
  },
  {
    "No": "[38]",
    "Year": "2025",
    "Category": "Imaging & Display",
    "Keywords": "UDC, Metasurface Imaging, Wavefront Restoration, Under-Display Camera",
    "Title": "Inverse-Designed Metasurfaces for Wavefront Restoration in Under-Display Camera Systems",
    "Authors": "J. Jo†, M. Lee†, [[b]]S. Lee†[[/b]], [[b]]C. Kang[[/b]], [[b]]H. Chung*[[/b]]",
    "Journal": "Nanophotonics (2025) (IF:7.5)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1ktzVHteJH2vMqlbvQ-4pVZ6rJqyuRbkK&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "UDC / Metasurface Imaging",
    "Note": "",
    "MemberKeys": "seunghyeon-lee; chanik-kang; haejun-chung"
  },
  {
    "No": "[37]",
    "Year": "2025",
    "Category": "Energy & Thermal Photonics",
    "Keywords": "Metamaterial Absorber, Inverse Design, Ultrathin Absorber",
    "Title": "Inverse design of ultrathin metamaterial absorber",
    "Authors": "[[b]]E. Jang†[[/b]], J. Cho†, [[b]]C. Kang*[[/b]], [[b]]H. Chung*[[/b]]",
    "Journal": "Nanomaterials (2025) (IF:4.3)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1XxD1rY72YSujx77MDF5kXCeaJvBGATAY&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Metamaterial Absorber",
    "Note": "",
    "MemberKeys": "eunbi-jang; chanik-kang; haejun-chung"
  },
  {
    "No": "[36]",
    "Year": "2025",
    "Category": "Energy & Thermal Photonics",
    "Keywords": "Radiative Cooling, Thermal Photonics, Manufacturing, Applications",
    "Title": "Design strategies, manufacturing, and applications of radiative cooling technologies",
    "Authors": "[[b]]Joonho Kang†[[/b]], [[b]]Changkyun Lee†[[/b]], [[b]]Haejun Chung*[[/b]] and Peter Bermel*",
    "Journal": "Nanophotonics (2025) (IF:7.5)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1u6pSkcVYBcCa_GIAFRwI4ayHcuZsNMg6&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Radiative Cooling",
    "Note": "",
    "MemberKeys": "joonho-kang; changkyun-lee; haejun-chung"
  },
  {
    "No": "[35]",
    "Year": "2025",
    "Category": "Materials & Light-Matter Interaction",
    "Keywords": "Chiral Nanophotonics, Helical Dichroism, Inverse Design",
    "Title": "Inverse Design of Chiral Structures for Giant Helical Dichroism",
    "Authors": "C.-C. Pan†, [[b]]M. Bae†[[/b]], H. Wang, J. Lim, R. R. Unnithan, J. Yang, [[b]]H. Chung*[[/b]], S. Kim*",
    "Journal": "Nanoscale Horizons (2025) (IF:8.0) (Invited)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1zPdIKhdCu4YDOKBMWHW46DU1paMR3qxH&sz=w600",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Chiral Nanophotonics",
    "Note": "",
    "MemberKeys": "munseong-bae; haejun-chung"
  },
  {
    "No": "[34]",
    "Year": "2025",
    "Category": "Integrated Photonics & Quantum",
    "Keywords": "Thin-Film Lithium Niobate, Mode Converter, Photon-pair Generation, Freeform Photonics",
    "Title": "Freeform Thin-Film Lithium Niobate Mode Converter for Photon-pair Generation",
    "Authors": "C. Kim†, [[b]]M. Bae†[[/b]], [[b]]M. Choi[[/b]], [[b]]S. Lee[[/b]], M. Lee, H. Jung, [[b]]H. Chung*[[/b]], [[b]]H. Kwon*[[/b]]",
    "Journal": "Nanophotonics (2025) (IF:7.5)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUBdlAMQ8o0ntISnX16Fc0jh6nE1LlJy84q8fzgUtGronNsWJaXBq1_qkC8MHmb2UcYfhBw0IA5zeLR8K3lm1_QujovGt4UwGiuK91HEPPgpqs9B1lXtunwiQ3XRNR1Sbh9_AhvqghTfQOQVFaUUd0ySYsUdmD-eCe1oCVhIoj-waa8_ld4B7ldBSjbVhu1RFzb66rnGR3zMV5lFN1wLXRxzXhKWd56_gOvw%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Integrated Photonics",
    "Note": "",
    "MemberKeys": "munseong-bae; minho-choi; seunghyeon-lee; haejun-chung; hyounghan-kwon"
  },
  {
    "No": "[33]",
    "Year": "2025",
    "Category": "AI & Computational Design",
    "Keywords": "Neural Operator, Fourier Neural Operator, Surrogate Solver, Metasurface, Wavefront Shaping",
    "Title": "Adjoint Method-based Fourier Neural Operator Surrogate Solver for Wavefront Shaping in Tunable Metasurfaces",
    "Authors": "[[b]]C. Kang†[[/b]], J. Seo†, [[b]]I. Jang[[/b]], [[b]]H. Chung*[[/b]]",
    "Journal": "iScience (2025) (IF:6.107)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUAJIy21Znbf_W7XaWv62LidUWw73927ACfOKoRRn9nc8Xel-h0M9phQ9NN7Sl2rv9sUplx5r4OnjuFcRIipU8b7_WSG779g-6nj_cQQzfjO_UJhdBGUXT_65W11qYhMdvGUvzfvyObmzx5GimJHBOZsQlr02NJLZdgUqkejJNEInwFXou6AK1Dx%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Neural Operator / Metasurface",
    "Note": "",
    "MemberKeys": "chanik-kang; ikbeom-jang; haejun-chung"
  },
  {
    "No": "[32]",
    "Year": "2024",
    "Category": "Imaging & Display",
    "Keywords": "AI, Metalens Imaging, Deep Learning, End-to-End Imaging, Metasurfaces",
    "Title": "Deep-learning-driven end-to-end metalens imaging Metasurfaces",
    "Authors": "J. Seo†, J. Jo†, J. Kim†, [[b]]J. Kang†[[/b]], [[b]]C. Kang[[/b]], S. Moon, E. Lee, [[b]]J. Hong[[/b]], J. Rho*, [[b]]H. Chung*[[/b]]",
    "Journal": "Advanced Photonics 6(6), 066002 (2024) (IF:20.6, JCR~2.9% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Metalens Imaging / Deep Learning",
    "Note": "",
    "MemberKeys": "joonho-kang; chanik-kang; jaehyun-hong; haejun-chung"
  },
  {
    "No": "[31]",
    "Year": "2024",
    "Category": "Biomedical AI",
    "Keywords": "AI, Medical Imaging, Dermatology, Segmentation, Weak Supervision, Texture Map",
    "Title": "Facial Wrinkle Segmentation for Cosmetic Dermatology: Pretraining with Texture Map-Based Weak Supervision",
    "Authors": "[[b]]J. Moon[[/b]], [[b]]H. Chung*[[/b]], [[b]]I. Jang*[[/b]]",
    "Journal": "[ICPR] The International Conference on Pattern Recognition (2024) (BK21 Conference)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Dermatology Segmentation",
    "Note": "",
    "MemberKeys": "junho-moon; haejun-chung; ikbeom-jang"
  },
  {
    "No": "[30]",
    "Year": "2024",
    "Category": "Nanophotonics & Inverse Design",
    "Keywords": "AI, Diffusion Model, Inverse Design, Photonic Structures, Physics-guided Optimization",
    "Title": "Physics-guided Optimization of Photonic Structures using Denoising Diffusion Probabilistic Models",
    "Authors": "D. Seo†, S. Um†, S. Lee, J. Ye*, [[b]]H. Chung*[[/b]]",
    "Journal": "NeurIPS W Machine Learning and the Physical Science (2024)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Inverse Design / Diffusion Model",
    "Note": "Workshop",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[29]",
    "Year": "2024",
    "Category": "AI & Computational Design",
    "Keywords": "Neural Operator, Electromagnetic Field Prediction, Wavelength Interpolation, Physics-guided Simulation, Nanophotonics",
    "Title": "Wave Interpolation Neural Operator: Interpolated Prediction of Electric Fields Across Untrained Wavelengths",
    "Authors": "J. Seo†, [[b]]C. Kang†[[/b]], D. Seo, [[b]]H. Chung*[[/b]]",
    "Journal": "NeurIPS W Data-driven and Differentiable Simulations, Surrogates, and Solvers (2024)",
    "Link": "https://arxiv.org/abs/2408.02971",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Neural Operator",
    "Note": "Workshop",
    "MemberKeys": "chanik-kang; haejun-chung"
  },
  {
    "No": "[28]",
    "Year": "2024",
    "Category": "Nanophotonics & Inverse Design",
    "Keywords": "Photonic Inverse Design, Large-scale Optimization, Computational Photonics, Topology Optimization",
    "Title": "Large-scale photonic inverse design: computational challenges and breakthroughs",
    "Authors": "[[b]]C. Kang†[[/b]], C. Park†, M. Lee+, [[b]]J. Kang[[/b]], M. Jang*, [[b]]H. Chung*[[/b]]",
    "Journal": "Nanophotonics (2024) (IF:8.45, JCR~6.7% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Photonic Inverse Design",
    "Note": "",
    "MemberKeys": "chanik-kang; joonho-kang; haejun-chung"
  },
  {
    "No": "[27]",
    "Year": "2024",
    "Category": "Imaging & Display",
    "Keywords": "Color Router, CMOS Image Sensor, Nanophotonics, Subwavelength Pixels, High Efficiency",
    "Title": "Towards subwavelength pixels: Nanophotonic color routers for ultra-compact high-efficiency CMOS image sensors",
    "Authors": "C. Park†, [[b]]S. Lee†[[/b]], T. Lee, [[b]]J. Kang[[/b]], J. Jeon, C. Park, S. Kim, [[b]]H. Chung*[[/b]], M. Jang*",
    "Journal": "Journal of Optics (2024)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Color Router / CMOS Image Sensor",
    "Note": "",
    "MemberKeys": "seunghyeon-lee; joonho-kang; haejun-chung"
  },
  {
    "No": "[26]",
    "Year": "2024",
    "Category": "Imaging & Display",
    "Keywords": "Color Router, CMOS Image Sensor, Inverse Design, Interpixel Crosstalk, Nanophotonics",
    "Title": "Inverse Design of Color Routers in CMOS Image Sensors: Toward Minimizing Interpixel",
    "Authors": "[[b]]S. Lee†[[/b]], [[b]]J. Hong†[[/b]], [[b]]J. Kang[[/b]], J. Park, J. Lim, T. Lee, M. Jang, [[b]]H. Chung*[[/b]]",
    "Journal": "Nanophotonics (2024) (IF:8.45, JCR~6.7% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Color Router / Inverse Design",
    "Note": "",
    "MemberKeys": "seunghyeon-lee; jaehyun-hong; joonho-kang; haejun-chung"
  },
  {
    "No": "[25]",
    "Year": "2024",
    "Category": "Materials & Light-Matter Interaction",
    "Keywords": "2D Materials, WS2, Chiral Metasurface, Geometric Phase, Inverse Design",
    "Title": "Inverse Designed WS2 Planar Chiral Metasurface with Geometric Phase",
    "Authors": "J. Jo, [[b]]S. Lee[[/b]], [[b]]M. Bae[[/b]], D. Nelson, K. Crozier, N. Yu, [[b]]H. Chung*[[/b]], S. Kim*",
    "Journal": "Journal of Optics (2024)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "2D Materials / Chiral Metasurface",
    "Note": "",
    "MemberKeys": "seunghyeon-lee; munseong-bae; haejun-chung"
  },
  {
    "No": "[24]",
    "Year": "2024",
    "Category": "AI & Computational Design",
    "Keywords": "Adjoint Method, Machine Learning, Inverse Design, Photonic Devices, Computational Optimization",
    "Title": "Adjoint Method in Machine Learning: A Pathway to Efficient Inverse Design of Photonic Devices",
    "Authors": "[[b]]C. Kang+[[/b]], D. Seo+, S. V. Boriskina, [[b]]H. Chung*[[/b]]",
    "Journal": "Materials & Design (2024) (IF:8.40)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Adjoint Method / Machine Learning",
    "Note": "",
    "MemberKeys": "chanik-kang; haejun-chung"
  },
  {
    "No": "[23]",
    "Year": "2023",
    "Category": "Energy & Thermal Photonics",
    "Keywords": "Optical Vortex, Thin-Film Absorption, Inverse Design, Nanophotonics, Absorption Enhancement",
    "Title": "Inverse design and optical vortex manipulation for thin film absorption enhancement",
    "Authors": "[[b]]M. Bae[[/b]], J. Jo, M. Lee, [[b]]J. Kang[[/b]], S. V. Boriskina*, [[b]]H. Chung*[[/b]]",
    "Journal": "Nanophotonics (2023) (IF:8.45, JCR~6.7% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Thin-Film Absorption / Optical Vortex",
    "Note": "",
    "MemberKeys": "munseong-bae; joonho-kang; haejun-chung"
  },
  {
    "No": "[22]",
    "Year": "2023",
    "Category": "Imaging & Display",
    "Keywords": "Color Splitter, Image Sensor, Freeform Design, Subwavelength Pixels, Nanophotonics",
    "Title": "Design parameters of free-form color splitters for subwavelength pixelated image sensors",
    "Authors": "S. Kim, C. Park, S. Kim, [[b]]H. Chung[[/b]], M. Jang*",
    "Journal": "iScience (2023) (IF:6.1)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Color Splitter / Image Sensor",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[21]",
    "Year": "2023",
    "Category": "Nanophotonics & Inverse Design",
    "Keywords": "Metalens, High-NA, Maskless Lithography, Inverse Design, Nanophotonics",
    "Title": "Inverse Design of High-NA Metalens for Maskless Lithography",
    "Authors": "[[b]]C. Kang+[[/b]], D. Seo+, S. V. Boriskina, [[b]]H. Chung*[[/b]]",
    "Journal": "Nanophotonics (2023) (IF:8.45, JCR~6.7% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Metalens / Maskless Lithography",
    "Note": "",
    "MemberKeys": "chanik-kang; haejun-chung"
  },
  {
    "No": "[20]",
    "Year": "2022",
    "Category": "Energy & Thermal Photonics",
    "Keywords": "FDTD, Dispersive Media, Radiative Cooling, Thermal Photonics, Electromagnetic Simulation",
    "Title": "Modeling dispersive media in finite-difference time-domain method for radiative cooling applications",
    "Authors": "[[b]]M. Bae[[/b]], [[b]]H. Chung*[[/b]]",
    "Journal": "IEEE Access (2022) (IF:3.37, JCR~34.2% in Eng.)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Radiative Cooling / FDTD",
    "Note": "",
    "MemberKeys": "munseong-bae; haejun-chung"
  },
  {
    "No": "[19]",
    "Year": "2022",
    "Category": "Nanophotonics & Inverse Design",
    "Keywords": "Electromagnetic Transparency, Short-Wavelength Infrared, Angle-Independent Response, Nanophotonics",
    "Title": "Numerical Demonstration of Angle-Independent Electromagnetic Transparency in Short-Wavelength Infrared Regime",
    "Authors": "J. Park, S. Hong, [[b]]H. Chung*[[/b]]",
    "Journal": "IEEE Access (2022) (IF:3.37, JCR~34.2% in Eng.)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Electromagnetic Transparency / SWIR",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[18]",
    "Year": "2022",
    "Category": "Nanophotonics & Inverse Design",
    "Keywords": "Nano-LED, Directional Emission, Inverse Design, Computational Limit, Nanophotonics",
    "Title": "Computational upper-limit of directional light emission in nano-LED via inverse design",
    "Authors": "[[b]]H. Chung*[[/b]]",
    "Journal": "Optics Express 30(6) (2022) (IF:3.67, JCR~19.1% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Nano-LED / Directional Emission",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[17]",
    "Year": "2022",
    "Category": "Integrated Photonics & Quantum",
    "Keywords": "Waveguide Biosensor, Inverse Design, Biomolecule Detection, Single-Frequency Detection, Nanophotonics",
    "Title": "Inverse-designed waveguide-based biosensor for high-sensitivity, single-frequency detection of biomolecules",
    "Authors": "[[b]]H. Chung*[[/b]], J. Park, S. V. Boriskina*",
    "Journal": "Nanophotonics (2022) (IF:8.45, JCR~6.7% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Waveguide Biosensor",
    "Note": "Won a paper award in KIEES conference",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[16]",
    "Year": "2022",
    "Category": "Nanophotonics & Inverse Design",
    "Keywords": "Freeform Optimization, Nanophotonic Devices, Deep Learning, Classical Optimization, Inverse Design",
    "Title": "Free-form optimization of nanophotonic devices: from classical methods to deep learning",
    "Authors": "J. Park, S. Kim, D. W. Nam, [[b]]H. Chung*[[/b]], C. Y. Park*, and M. S. Jang*",
    "Journal": "Nanophotonics (2022) (IF:8.45, JCR~6.7% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Freeform Optimization / Nanophotonic Devices",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[15]",
    "Year": "2021",
    "Category": "Integrated Photonics & Quantum",
    "Keywords": "Diffractive Biosensor, Inverse Design, Reporter Cleavage Detection, Single-Frequency Detection",
    "Title": "Inverse design of a single-frequency diffractive biosensor based on the reporter cleavage detection mechanism",
    "Authors": "[[b]]H. Chung*[[/b]], S. V. Boriskina*",
    "Journal": "Optics Express 29(7) (2021) (IF:3.67, JCR~19.1% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Diffractive Biosensor",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[14]",
    "Year": "2021",
    "Category": "Materials & Light-Matter Interaction",
    "Keywords": "Porous Silicon Sensor, Optical Biosensing, Cleavage Detection, Sensor Sensitivity",
    "Title": "High contrast cleavage detection for enhancing porous silicon sensor sensitivity",
    "Authors": "R. Layouni, M. Dubrovsky, M. Bao, [[b]]H. Chung[[/b]], K. Du, S. V. Boriskina, S. M. Weiss, and D. Vermeulen",
    "Journal": "Optics Express 29(1) (2021) (IF:3.67, JCR~19.1% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Porous Silicon Sensor",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[13]",
    "Year": "2020",
    "Category": "Nanophotonics & Inverse Design",
    "Keywords": "Tunable Metasurface, Inverse Design, Beam Steering, Angular Steering, Switching Efficiency",
    "Title": "Tunable metasurface inverse design for 80% switching efficiencies and 144° angular steering",
    "Authors": "[[b]]H. Chung*[[/b]], O. Miller*",
    "Journal": "ACS Photonics 7(8), 2236–2243 (2020) (IF:6.86, JCR~8.7% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Tunable Metasurface / Beam Steering",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[12]",
    "Year": "2020",
    "Category": "Nanophotonics & Inverse Design",
    "Keywords": "Metalens, High-NA, Achromatic Metalens, Inverse Design, Broadband Optics",
    "Title": "High-NA Achromatic Metalenses by Inverse Design",
    "Authors": "[[b]]H. Chung*[[/b]], O. Miller*",
    "Journal": "Optics Express 28(5), 6945-6965 (2020) (IF:3.67, JCR~19.1% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Achromatic Metalens",
    "Note": "Top-cited paper in Optics Express; highly cited paper (<1%) in Physics area by Clarivate",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[11]",
    "Year": "2020",
    "Category": "Nanophotonics & Inverse Design",
    "Keywords": "Electromagnetic Waves, Free-Space Concentration, Computational Bounds, Nanophotonics",
    "Title": "Maximal Free-Space Concentration of Electromagnetic Waves",
    "Authors": "H. Shim, [[b]]H. Chung[[/b]], O. Miller",
    "Journal": "Physical Review Applied 14(1), 014007 (2020) (IF:4.53, JCR~17.0% in Physics Applied)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Electromagnetic Wave Concentration",
    "Note": "Editors’ Suggestion",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[10]",
    "Year": "2018",
    "Category": "Materials & Light-Matter Interaction",
    "Keywords": "Gold Nanorod, Polymer Micelles, Ultrasound Contrast, Laser-Induced CO2 Generation, Nanomaterials",
    "Title": "Laser-Induced CO2 Generation from Gold Nanorod-Containing Poly(propylene carbonate)-Based Block Polymer Micelles for Ultrasound Contrast Enhancement",
    "Authors": "J. Lee, S. Jo, [[b]]H. Chung[[/b]], W. Um, R. Chandrasekar, Y. Choi, V. M. Shalaev, Y.-Y. Won",
    "Journal": "ACS Applied Materials & Interfaces 10(31), 26084-26098 (2018)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Gold Nanorod / Ultrasound Contrast",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[9]",
    "Year": "2017",
    "Category": "Energy & Thermal Photonics",
    "Keywords": "Perovskite/Silicon Tandem Photovoltaics, Bifacial Tandem Cells, Optical Modeling, Solar Cells",
    "Title": "Modeling and designing multilayer 2D perovskite/silicon bifacial tandem photovoltaics for high efficiencies and long-term stability",
    "Authors": "[[b]]H. Chung[[/b]], X. Sun, R. Singh, L. Kumar, M. A. Alam, P. Bermel",
    "Journal": "Optics Express 25(8), A311-A322 (2017) (IF:3.15, JCR~14.6% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Perovskite/Silicon Tandem Photovoltaics",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[8]",
    "Year": "2017",
    "Category": "Energy & Thermal Photonics",
    "Keywords": "Thermophotovoltaics, Thermal Radiation Transfer, Maxwell’s Fish-Eye Lens, Collimated Radiation",
    "Title": "Collimated Thermal Radiation Transfer Via Half Maxwell’s Fish-Eye Lens for Thermophotovoltaics",
    "Authors": "[[b]]H. Chung[[/b]], Z. Zhou, P. Bermel",
    "Journal": "Applied Physics Letters 110(20), 201111 (2017)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Thermophotovoltaics / Thermal Radiation",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[7]",
    "Year": "2016",
    "Category": "Energy & Thermal Photonics",
    "Keywords": "Light Trapping, Thin-Film Solar Cells, CdZnTe/Si Tandem Cells, Hybrid Dielectric Design",
    "Title": "Hybrid dielectric light trapping designs for thin-film CdZnTe/Si tandem cells",
    "Authors": "[[b]]H. Chung[[/b]], C. Zhou, X. T. Tee, K.-Y. Jung, and P. Bermel",
    "Journal": "Optics Express 24(14) (2016) (IF:3.49, JCR~10.5% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Light Trapping / Tandem Solar Cells",
    "Note": "Featured in Light Trapping for Photovoltaics section",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[6]",
    "Year": "2016",
    "Category": "Energy & Thermal Photonics",
    "Keywords": "Perovskite/Silicon Tandem Cells, Optical Design, Solar Cells, Photovoltaics",
    "Title": "Optical approaches to improving perovskite/Si tandem cells",
    "Authors": "[[b]]H. Chung[[/b]], X. Sun and P. Bermel",
    "Journal": "MRS Advances 1(14) (2016)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Perovskite/Si Tandem Cells",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[5]",
    "Year": "2015",
    "Category": "Energy & Thermal Photonics",
    "Keywords": "Nanoplasmonics, Thin-Film Silicon Solar Cells, Parasitic Absorption, FDTD, Flux Plane Simulation",
    "Title": "Flexible flux plane simulations of parasitic absorption in nanoplasmonic thin-film silicon solar cells",
    "Authors": "[[b]]H. Chung[[/b]], K.-Y. Jung and P. Bermel",
    "Journal": "Optical Materials Express 5(9) (2015) (IF:2.92, JCR~15.9% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Nanoplasmonic Solar Cells / FDTD",
    "Note": "Published in a Plasmonics special issue",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[4]",
    "Year": "2015",
    "Category": "Energy & Thermal Photonics",
    "Keywords": "CdZnTe/Si Tandem Solar Cells, Photovoltaics, Optical Design, Tandem Junction",
    "Title": "Design of CdZnTe and Crystalline Silicon Tandem Junction Solar Cells",
    "Authors": "C. Zhou, [[b]]H. Chung[[/b]], X. Wang and P. Bermel",
    "Journal": "IEEE Journal of Photovoltaics 6(1) (2015) (IF:3.00, JCR~6.3% in Physics, Applied)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "CdZnTe/Si Tandem Solar Cells",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[3]",
    "Year": "2015",
    "Category": "AI & Computational Design",
    "Keywords": "FDTD, Dispersive Media, Rational Function, Particle Swarm Optimization, Electromagnetic Simulation",
    "Title": "Accurate FDTD modeling for dispersive media using rational function and particle swarm optimisation",
    "Authors": "[[b]]H. Chung[[/b]], S. Ha, J. Cho and K.-Y. Jung",
    "Journal": "International Journal of Electronics 102(7) (2015)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "FDTD / Dispersive Media",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[2]",
    "Year": "2014",
    "Category": "Energy & Thermal Photonics",
    "Keywords": "Time-Domain Simulation, Tandem Silicon Solar Cells, Light Trapping, Rational Function, FDTD",
    "Title": "Time domain simulation of tandem silicon solar cells with optimal textured light trapping enabled by the quadratic complex rational function",
    "Authors": "[[b]]H. Chung[[/b]], K.-Y. Jung, X. T. Tee and P. Bermel",
    "Journal": "Optics Express 22(103) (2014) (IF:3.55, JCR~5.0% in Optics)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Tandem Silicon Solar Cells / Light Trapping",
    "Note": "",
    "MemberKeys": "haejun-chung"
  },
  {
    "No": "[1]",
    "Year": "2013",
    "Category": "Materials & Light-Matter Interaction",
    "Keywords": "Dispersive FDTD, Concrete Materials, Electromagnetic Modeling, Material Dispersion",
    "Title": "Dispersive FDTD modeling for concrete materials",
    "Authors": "[[b]]H. Chung[[/b]], J. Cho, S. Ha, S. Ju and K.-Y. Jung",
    "Journal": "ETRI Journal 35(5) (2013)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Dispersive FDTD / Concrete Materials",
    "Note": "",
    "MemberKeys": "haejun-chung"
  }
];

window.AWARDS = [
  {
    "Date": "2026-04",
    "Year": "2026",
    "Title": "Haejun received the Commendation from the Deputy Prime Minister for Science and Technology",
    "Recipient": "Haejun Chung",
    "Award": "Commendation from the Deputy Prime Minister for Science and Technology",
    "Organization": "Ministry of Science and ICT",
    "Category": "Commendation",
    "Image": "",
    "Link": "",
    "Description": "Haejun received the Commendation from the Deputy Prime Minister for Science and Technology.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2026-02",
    "Year": "2026",
    "Title": "Junho, Eunbi, Daehwan, and Jiwoong received Grand Prize from HY-BK G3 program",
    "Recipient": "Junho, Eunbi, Daehwan, Jiwoong",
    "Award": "Grand Prize",
    "Organization": "HY-BK G3 program",
    "Category": "Prize",
    "Image": "",
    "Link": "",
    "Description": "Junho, Eunbi, Daehwan, and Jiwoong received Grand Prize from HY-BK G3 program.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2026-01",
    "Year": "2026",
    "Title": "Eunbi and Jiwoong received Bronze Prize from BK21 IC-PBL+ Graduate Championship",
    "Recipient": "Eunbi, Jiwoong",
    "Award": "Bronze Prize",
    "Organization": "BK21 IC-PBL+ Graduate Championship",
    "Category": "Prize",
    "Image": "",
    "Link": "",
    "Description": "Eunbi and Jiwoong received Bronze Prize from BK21 IC-PBL+ Graduate Championship.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2025-12",
    "Year": "2025",
    "Title": "Chanik, Hyewon, and Munseong received Excellence Award in Startup Competition",
    "Recipient": "Chanik, Hyewon, Munseong",
    "Award": "Excellence Award",
    "Organization": "Startup Competition",
    "Category": "Competition Award",
    "Image": "",
    "Link": "",
    "Description": "Chanik, Hyewon, and Munseong received Excellence Award in Startup Competition.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2025-11",
    "Year": "2025",
    "Title": "EIDL team won the TTA Award of 2025 AI-Champion Contest",
    "Recipient": "EIDL team",
    "Award": "TTA Award",
    "Organization": "2025 AI-Champion Contest",
    "Category": "Competition Award",
    "Image": "",
    "Link": "",
    "Description": "EIDL team won the TTA Award of the Ministry of Science and ICT 2025 AI-Champion Contest.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2025-08",
    "Year": "2025",
    "Title": "Eunbi, Junghee, and Chanik received 1st Place Award at KIEES Summer Conference",
    "Recipient": "Eunbi, Junghee, Chanik",
    "Award": "1st Place Award",
    "Organization": "KIEES Summer Conference",
    "Category": "Paper Award",
    "Image": "",
    "Link": "",
    "Description": "Eunbi, Junghee, and Chanik received 1st Place Award among 780 papers from KIEES Summer Conference.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2025-08",
    "Year": "2025",
    "Title": "Chanik, Munseong, Joonhyuk, and Hyewon received Award from HY-BK G3 program",
    "Recipient": "Chanik, Munseong, Joonhyuk, Hyewon",
    "Award": "Award",
    "Organization": "HY-BK G3 program",
    "Category": "Prize",
    "Image": "",
    "Link": "",
    "Description": "Team Finale received Award from HY-BK G3 program.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2025-01",
    "Year": "2025",
    "Title": "EIDL team won two CES 2025 Innovation Awards",
    "Recipient": "EIDL team",
    "Award": "CES 2025 Innovation Awards",
    "Organization": "CES 2025",
    "Category": "Innovation Award",
    "Image": "",
    "Link": "",
    "Description": "EIDL team won two CES 2025 Innovation Awards for the ultra-compact metalens imaging system.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2024-11",
    "Year": "2024",
    "Title": "Ultra-compact metalens imaging technique awarded two CES 2025 Innovation Awards",
    "Recipient": "EIDL team",
    "Award": "CES 2025 Innovation Awards",
    "Organization": "CES 2025",
    "Category": "Innovation Award",
    "Image": "",
    "Link": "",
    "Description": "Ultra-compact metalens imaging technique was awarded two CES 2025 Innovation Awards.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2024-08",
    "Year": "2024",
    "Title": "EIDL team received Silver Prize and Bronze Prize from Corning AI Challenge",
    "Recipient": "Chanik, Junyoung, Dongjin",
    "Award": "Silver Prize and Bronze Prize",
    "Organization": "Corning AI Challenge",
    "Category": "Competition Award",
    "Image": "",
    "Link": "",
    "Description": "EIDL team received Silver Prize in 2023 and Bronze Prize in 2024 from Corning AI Challenge.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2024-08",
    "Year": "2024",
    "Title": "Chanik, Munseong, and Joonhyuk received Silver Prize from HY-BK G3 program",
    "Recipient": "Chanik, Munseong, Joonhyuk",
    "Award": "Silver Prize",
    "Organization": "HY-BK G3 program",
    "Category": "Prize",
    "Image": "",
    "Link": "",
    "Description": "Team INR received Silver Prize from HY-BK G3 program.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2023-12",
    "Year": "2023",
    "Title": "Dongjin, Junho, and Joonhyuk received Silver Prize from AI Grand Challenge",
    "Recipient": "Dongjin, Junho, Joonhyuk",
    "Award": "Silver Prize",
    "Organization": "AI Grand Challenge",
    "Category": "Competition Award",
    "Image": "",
    "Link": "",
    "Description": "Team Gaia received Silver Prize from AI Grand Challenge.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2023-11",
    "Year": "2023",
    "Title": "Joonho's team received Bronze Prize from Capstone Design Fair 2023",
    "Recipient": "Joonho's team",
    "Award": "Bronze Prize",
    "Organization": "Capstone Design Fair 2023",
    "Category": "Competition Award",
    "Image": "",
    "Link": "",
    "Description": "Joonho's team received Bronze Prize from Capstone Design Fair 2023.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2023-11",
    "Year": "2023",
    "Title": "Joonho's team received Bronze Prize from HY-EE Graduation Project Competition 2023",
    "Recipient": "Joonho's team",
    "Award": "Bronze Prize",
    "Organization": "HY-EE Graduation Project Competition 2023",
    "Category": "Competition Award",
    "Image": "",
    "Link": "",
    "Description": "Joonho's team received Bronze Prize from HY-EE Graduation Project Competition 2023.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2023-11",
    "Year": "2023",
    "Title": "Joonhyuk received Paper Award from KIEES Fall 2023",
    "Recipient": "Joonhyuk",
    "Award": "Paper Award",
    "Organization": "KIEES Fall Conference 2023",
    "Category": "Paper Award",
    "Image": "",
    "Link": "",
    "Description": "Joonhyuk received Paper Award from KIEES Fall 2023.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2023-11",
    "Year": "2023",
    "Title": "EIDL received Grand Prize from Healthy Research Lab Culture Contest",
    "Recipient": "EIDL",
    "Award": "Grand Prize",
    "Organization": "Healthy Research Lab Culture Contest",
    "Category": "Prize",
    "Image": "",
    "Link": "",
    "Description": "EIDL received Grand Prize from Healthy Research Lab Culture Contest.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2023-10",
    "Year": "2023",
    "Title": "Haejun was awarded as a Rising Star in EIRIC",
    "Recipient": "Haejun Chung",
    "Award": "Rising Star",
    "Organization": "EIRIC",
    "Category": "Recognition Award",
    "Image": "",
    "Link": "",
    "Description": "Haejun was awarded as a Rising Star in EIRIC.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2023-08",
    "Year": "2023",
    "Title": "Junjeong, Munseong, and Chanik received Grand Prize from HY-BK G3 program",
    "Recipient": "Junjeong, Munseong, Chanik",
    "Award": "Grand Prize",
    "Organization": "HY-BK G3 program",
    "Category": "Prize",
    "Image": "",
    "Link": "",
    "Description": "Junjeong, Munseong, and Chanik received Grand Prize from HY-BK G3 program.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2023-07",
    "Year": "2023",
    "Title": "JoonHyuk, Jaegang, and Haejun received Grand Prize from the 6th HY-Innovation Contest",
    "Recipient": "JoonHyuk, Jaegang, Haejun",
    "Award": "Grand Prize",
    "Organization": "6th HY-Innovation Contest",
    "Category": "Competition Award",
    "Image": "",
    "Link": "",
    "Description": "JoonHyuk, Jaegang, and Haejun received Grand Prize from the 6th HY-Innovation Contest.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2023-04",
    "Year": "2023",
    "Title": "Jaegang received the HY-KIST Global Talented Student Award",
    "Recipient": "Jaegang",
    "Award": "HY-KIST Global Talented Student Award",
    "Organization": "HY-KIST",
    "Category": "Student Award",
    "Image": "",
    "Link": "",
    "Description": "Jaegang received the HY-KIST Global Talented Student Award.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2022-08",
    "Year": "2022",
    "Title": "Haejun won the ASML TECH TALK 2022 Paper Award",
    "Recipient": "Haejun Chung",
    "Award": "ASML TECH TALK 2022 Paper Award",
    "Organization": "ASML TECH TALK 2022",
    "Category": "Paper Award",
    "Image": "",
    "Link": "",
    "Description": "Haejun won the ASML TECH TALK 2022 Paper Award.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  },
  {
    "Date": "2021-11",
    "Year": "2021",
    "Title": "Junjeong Park won Paper Award at KIEES Fall Conference",
    "Recipient": "Junjeong Park",
    "Award": "Paper Award",
    "Organization": "KIEES Fall Conference",
    "Category": "Paper Award",
    "Image": "",
    "Link": "",
    "Description": "Junjeong Park won Paper Award at KIEES Fall Conference.",
    "Featured": "FALSE",
    "Visible": "TRUE"
  }
];
